apiVersion: batch/v1
kind: Job
metadata:
  name: purdue-cms-broker-kaniko-build
  namespace: cms-dev
  labels:
    app: purdue-cms-broker-kaniko-build
spec:
  ttlSecondsAfterFinished: 300  # Clean up after 5 minutes
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
        - --context=git://github.com/kondratyevd/purdue-af-vscode.git
        - --context-sub-path=broker
        - --destination=geddes-registry.rcac.purdue.edu/cms/purdue-cms-broker:latest
        - --destination=geddes-registry.rcac.purdue.edu/cms/purdue-cms-broker:v1.0.0
        - --cache=true
        - --cache-repo=geddes-registry.rcac.purdue.edu/cms/purdue-cms-broker-cache
        - --compressed-caching=false
        - --single-snapshot
        - --cleanup
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
      volumes:
      - name: kaniko-secret
        secret:
          secretName: geddes-registry-secret
          items:
          - key: .dockerconfigjson
            path: config.json
