apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "broker.fullname" . }}
  labels:
    {{- include "broker.labels" . | nindent 4 }}
rules:
# Allow creating ServiceAccounts and RoleBindings in user namespaces
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["create", "delete", "get"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings"]
  verbs: ["create", "delete", "get"]
# Allow reading pods in user namespaces
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
# Allow creating tokens for ServiceAccounts
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "broker.fullname" . }}
  labels:
    {{- include "broker.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "broker.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "broker.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}













